# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f8a8322dc22709e88f343f7985a369f9b1a22ed007ee056cbad3e084391ad6045ae6b7c98c642b9b20a1f5d53a6711cf2ad26521c7044e0ab8171c5c17d006

test:
  secret_key_base: 7671d6b7a11981c859ba8bab920e29ef97d8784587921406672bdd3a33b3830b572ab31631fe9a6099daa43ffeb5719d1465d4fa4d9e634d17cd248e51343062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
